### ISSUE TITLE
Cannot find module 'glob' in getLernaPackages.js

### ISSUE THREAD

**Issue by janbiasi** [smollweide/lerna-terminal#1]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/4563751/35145995-ffb8a7be-fd09-11e7-9df6-7cd7b03a2676.png)

## Expected behavior
Command runs successfully

## Minimal reproduction of the problem with instructions
```bash
npm i -g lerna-terminal
lerna-terminal helpf
```

## Please tell us about your environment

<pre><code>
lerna-terminal version: 0.0.0-semantically-released

- Node version: 8
- Platform: Mac

Others:

</code></pre>

**Comment by smollweide** [comment]
Thanks a lot. Fixed in v1.1.2
